language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
  - "4"
before_script:
  - npm install chai chai-http mocha
  - npm install
  - npm install bcrypt
script: 
  - npm test
notifications:
  email: false